### ISSUE TITLE
3. Conversation Listing Screen

### ISSUE THREAD

**Issue by aayushkedia95** [samagra-comms/uci-console#15]
**Description** - Create a UI component to list down existing conversations, initiate process to add a new conversation

**Outcome**
1. Ability to edit, enable, disable, delete existing conversations
2. Ability to initiate the process of adding a new conversation

**Success Metrics**
1. List down all existing conversations
2. Successfully initiate adding a new conversation

**Functional Requirements**
1. View existing conversations in a tabular format - Name of the Bot, Status, Description, User Segments, Users, Action
-  Status = Live, Draft, Disabled
- Users = total count of users across multiple user segments for that conversation
- Action button to have the following options - Edit, Disable (when live), Enable (when disabled)
2. Search from existing conversations - Search by name of the bot
3. Add a new conversation - 'Add New' Button to redirect to [add a new conversation screen](https://github.com/Samagra-Development/UCI-Console/issues/16)

**Non-Functional Requirements**
Telemetry: Instrumentation should help find out -
a) In a day, how many users (unique and total) are visiting the UCI landing screen
b) In a day, how many users (unique and total) are clicking on 'Add New' button

**Additional Dependencies on other Components**
NA

**Links**
Wireframes - 
![1  Conversation list@2x_Updated](https://user-images.githubusercontent.com/80503666/121286803-fc4b3380-c8fd-11eb-859d-f40c294c34c4.jpeg)

APIs - [Link](https://www.postman.com/collections/437e7d1fc9f04ea2ce3e)

**Comment by bharatkashyap** [comment]
The `conversations-all` [component](https://github.com/Samagra-Development/UCI-Console/blob/release-4.0.0/projects/uci-console/src/lib/components/conversations/conversation-all.component.ts) - rendered at the "/uci/conversations" path in the portal - will have this table of conversations.

The `uci-service` [service](https://github.com/Samagra-Development/UCI-Console/blob/release-4.0.0/projects/uci-console/src/lib/services/uci.service.ts) will implement a GET call to `/bots` to fetch the list of conversations to be displayed.

**Comment by aayushkedia95** [comment]
*Changes*

- [x]   Back bar - Full width
- [x]   Blue color variance to be corrected
- [x]   UCI in one line
- [x]   Column widths to be corrected

**Comment by aayushkedia95** [comment]
*Changes*

- [x] Status to be bound - @ChakshuGautam 
- [x] Segments to be bound - @manojSRawat
- [x] Action - Disable to be added - @manojSRawat
- [x] Edit to be bound - @manojSRawat
- [x] Delete to be bound - @manojSRawat
- [x] Search API not working - @manojSRawat
