### ISSUE TITLE
2. UCI URL in Diksha Admin Login

### ISSUE THREAD

**Issue by aayushkedia95** [samagra-comms/uci-console#21]
[Link to Sunbird Ed JIRA Ticket](https://project-sunbird.atlassian.net/browse/SB-25041)

**Comment by bharatkashyap** [comment]
- An entry in the `main-header` [component](https://github.com/Samagra-Development/SunbirdEd-portal/blob/release-4.0.0/src/app/client/src/app/modules/core/components/main-header/main-header.component.html) _(Github link to component)_ is required to be added, with the navigation path to be set to **`uci/conversations`**.

- Please use the [sprite](https://github.com/Samagra-Development/SunbirdEd-portal/blob/release-4.0.0/src/app/client/src/assets/images/sprite.svg)  `#dashboard` as the placeholder icon for this entry in the sidebar 

- Set the label to be **`UCI`**
